branch-defaults:
  default:
    environment: Sample-env
  master:
    environment: bookswap
    group_suffix: null
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: ggcbookswap
  branch: null
  default_ec2_keyname: bookswap
  default_platform: PHP 5.4
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
